// THE PUBLIC API of @game-presets/desks — the one door a consumer comes through.
// A standalone imports from "@game-presets/desks", never a path into src.
export {
  BOARD,
  CHESS_SEATS,
  CHESS_UNIT,
  chessMap,
  chessRoom,
  COMMON as CHESS_COMMON,
  installChessArt,
  isCell,
  pictureOf,
  seatPlaces as chessPlaces,
  shadowOf,
  squareAt,
  type Figure,
} from "./chessMap.js";
export {
  checkerSurface,
  installNardyArt,
  mayThrow,
  NARDY_BUMP,
  NARDY_SEATS,
  NARDY_UNIT,
  nardyMap,
  nardyRoom,
  numberOf,
  isChecker,
  isPoint,
  pointAt,
  pointUnder,
  regripDice,
  runOf,
  seatOf,
  seatPlaces as nardyPlaces,
  seatsOf,
  settled,
  takes,
  wallsOf,
} from "./nardyMap.js";
export {
  growHand,
  HAND,
  HAND_LOCK,
  HAND_VALUE,
  handAccept,
  handId,
  handLocked,
  handOwner,
  handSurface,
  handTakes,
  handZone,
  installHandArt,
  isHand,
  placeHand,
  setHandLock,
} from "./handZone.js";
export {
  CHAIR,
  CHAIR_VALUE,
  chairId,
  chairSurface,
  installSeatArt,
  isChair,
  SEAT_TEXT,
  seatChair,
  seatChairs,
  type SeatLook,
  type SeatOfDesk,
} from "./seatPlace.js";
export { installLiveArt, LIVE, LIVE_UNIT, liveMap, liveTune, SEATS } from "./liveMap.js";
export { installRoundArt, ROUND_R, ROUND_SURFACE, roundMap, roundRoom, roundWalls, seatPlaces as roundPlaces } from "./roundMap.js";
export {
  ANCHOR_MARK,
  CASTS,
  deskRoom,
  fitStep,
  handLayout,
  installMapArt,
  KNIGHT,
  KNIGHT_SURFACE,
  LAMP,
  MAP,
  MAP_SURFACE,
  onTheDesk,
  PULL,
  PUT_DOWN,
  ROAM,
  svg,
  warmingNodes,
  zoneKeen,
  zoneLine,
  ZONE_SPREAD,
  type Spread,
} from "./felt.js";
