// THE PUBLIC API of @game-presets/desks — the one door a consumer comes through.
// A standalone imports from "@game-presets/desks", never a path into src.
export {
  BOARD,
  CHESS_SEATS,
  CHESS_UNIT,
  chessMap,
  chessRoom,
  COMMON as CHESS_COMMON,
  installChessArt,
  isCell,
  shadowOf,
  squareAt,
  type Figure,
} from "./chessMap.js";
export {
  installNardyArt,
  mayThrow,
  NARDY_SEATS,
  NARDY_UNIT,
  nardyMap,
  nardyRoom,
  numberOf,
  isChecker,
  isPoint,
  pointAt,
  pointUnder,
  regripDice,
  runOf,
  seatOf,
  seatsOf,
  settled,
  takes,
  wallsOf,
} from "./nardyMap.js";
export { installLiveArt, LIVE, LIVE_UNIT, liveMap, liveTune, SEATS } from "./liveMap.js";
export {
  ANCHOR_MARK,
  CASTS,
  deskRoom,
  fitStep,
  handLayout,
  installMapArt,
  KNIGHT,
  KNIGHT_SURFACE,
  LAMP,
  MAP,
  MAP_SURFACE,
  onTheDesk,
  PULL,
  PUT_DOWN,
  ROAM,
  svg,
  warmingNodes,
  zoneKeen,
  zoneLine,
  ZONE_SPREAD,
  type Spread,
} from "./felt.js";
