import { createRequire } from "module";
const require = createRequire(new URL("../server/scripts/x.mjs", import.meta.url));
const { chromium } = require("playwright");
const browser = await chromium.launch({ args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"] });
const cam = process.argv[2] ?? "top";
const p = await browser.newPage({ viewport: { width: 390, height: 844 } });
p.on("pageerror", (e) => console.log("PAGEERR", e.message));
await p.goto(`http://localhost:9590/?stand&cam=${cam}`);
await p.waitForFunction(() => window.__t3d && document.querySelector("#stage canvas"));
await p.waitForTimeout(1500);
const S = () => p.evaluate(() => { const s = window.__t3d.state(); const h = s.chairs.find((x) => x.owner === "me").hand; return { hand: h.length, felt: s.felt.length, piles: s.piles.map((q) => q.cards.length) }; });
console.log("start", JSON.stringify(await S()));
await p.evaluate(() => { window.__t3d.holdClock?.(null); });
const hid = await p.evaluate(() => window.__t3d.state().chairs.find((x) => x.owner === "me").hand[2].id);
let A = await p.evaluate((i) => window.__t3d.screenOf(i), hid);
await p.mouse.move(A.x, A.y); await p.mouse.down(); await p.mouse.move(A.x, A.y - 60, { steps: 4 }); await p.mouse.move(195, 380, { steps: 8 }); await p.mouse.up(); await p.waitForTimeout(1200);
console.log("out", JSON.stringify(await S()));
const felt = await p.evaluate(() => window.__t3d.state().felt.at(-1).id);
A = await p.evaluate((i) => window.__t3d.screenOf(i), felt);
console.log("felt at", JSON.stringify(A));
const refused = [];
await p.mouse.move(A.x, A.y); await p.mouse.down(); await p.mouse.move(A.x, A.y + 40, { steps: 4 });
await p.mouse.move(195, 780, { steps: 10 });
await p.waitForTimeout(500);
console.log("over hand", JSON.stringify(await p.evaluate(() => ({ drag: window.__t3d.draggingId(), held: window.__t3d.held?.() ?? null }))));
await p.mouse.up(); await p.waitForTimeout(1500);
console.log("back", JSON.stringify(await S()));
await browser.close();
