// ПЕРЕСАДКА СВОЕГО СТУЛА: кнопка открывает вид сверху со свободным зумом, без тел, рук, голов и карт в руках — только стол, стулья и карты на столе;
// свой стул тянут по кругу, «Готово» пересаживает, «Отмена» возвращает всё как было.
//   node reseat-check.mjs [base]     (стенд: `npm run dev`, порт 9590)
import { createRequire } from "module";
const require = createRequire(new URL("../server/scripts/x.mjs", import.meta.url));
const { chromium } = require("playwright");
const base = process.argv[2] ?? "http://localhost:9590";
const browser = await chromium.launch();
const p = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
p.on("pageerror", (e) => errors.push(e.message));
const checks = [];
const check = (name, ok, got) => checks.push({ name, ok, got });
await p.goto(`${base}/?stand&cam=head`);
await p.waitForFunction(() => window.__t3d && document.querySelector("#stage canvas"));
await p.waitForTimeout(1000);
const info = () => p.evaluate(() => window.__t3d.reseatInfo());
const mine = () => p.evaluate(() => { const c = window.__t3d.state().chairs.find((x) => x.owner === window.__t3d.me()); return { id: c.id, angle: c.angle }; });
const before = await info(), seat0 = await mine();
check("до пересадки: головы и карты в руке на месте", !before.on && before.heads && before.handShown > 0, before);
await p.locator("[data-reseat]:visible").first().click();
await p.waitForTimeout(800);
const on = await info();
check("пересадка: вид сверху, голов нет, карты в руках скрыты, стулья видны", on.on && !on.heads && on.chairs && on.handShown === 0, on);
check("свой стул светится, и только он", on.glow.length === 1 && on.glow[0] === seat0.id, on.glow);
const owners = await p.evaluate(() => window.__t3d.state().chairs.filter((c) => c.owner).map((c) => c.id));
check("над каждым занятым стулом кругляшок аватара", on.tags.length === owners.length && owners.every((id) => on.tags.includes(id)), { tags: on.tags, owners });
const ink = (await p.evaluate(() => window.__t3d.state().people.find((x) => x.key === window.__t3d.me()).ink)).replace("#", "").toLowerCase();
check("цвет моего стула тот же, что в игре, без подкраски; свечение — моего цвета", on.chair && on.chair.color === ink && on.chair.emissive === "000000" && on.chair.halo === ink, { on: on.chair, ink });
const fitOf = () => p.evaluate(() => { const w = innerWidth, h = innerHeight; return window.__t3d.chairs().map((c) => ({ id: c.id, in: c.x > 12 && c.x < w - 12 && c.y > 60 && c.y < h - 80, x: Math.round(c.x), y: Math.round(c.y) })); });
const fit = await fitOf();
check("при входе стол и все стулья влезают в кадр (портрет)", fit.length > 1 && fit.every((c) => c.in), fit);
check("камера смотрит сверху (орбита)", (await p.evaluate(() => window.__t3d.cam().mode)) === "orbit", null);
// Тянем свой стул: его экранное место — из хука `chairs()`.
const chair = await p.evaluate((id) => window.__t3d.chairs().find((c) => c.id === id), seat0.id);
await p.mouse.move(chair.x, chair.y); await p.mouse.down();
await p.mouse.move(chair.x + 120, chair.y - 60, { steps: 8 });
await p.mouse.up();
await p.waitForTimeout(400);
const chairPos = await p.evaluate((id) => window.__t3d.chairAt(id), seat0.id);
const angle = ((Math.atan2(chairPos[0], chairPos[2]) * 180) / Math.PI + 360) % 360;
check("свой стул уехал по кругу на другой угол", Math.abs(((angle - seat0.angle + 540) % 360) - 180) > 8, { angle, was: seat0.angle });
await p.locator("[data-reseat-no]:visible").click();
await p.waitForTimeout(600);
const off = await info();
check("«Отмена»: всё вернулось, свечения и кругляшков нет, стул на прежнем месте", !off.on && off.heads && off.glow.length === 0 && off.tags.length === 0 && (await mine()).angle === seat0.angle, { off, now: await mine() });
await p.locator("[data-reseat]:visible").first().click();
await p.waitForTimeout(600);
const c2 = await p.evaluate((id) => window.__t3d.chairs().find((c) => c.id === id), seat0.id);
await p.mouse.move(c2.x, c2.y); await p.mouse.down(); await p.mouse.move(c2.x + 120, c2.y - 60, { steps: 8 }); await p.mouse.up();
await p.waitForTimeout(300);
await p.locator("[data-reseat-ok]:visible").click();
await p.waitForTimeout(800);
const seat1 = await mine();
check("«Готово»: стул пересажен на новый угол", seat1.angle !== seat0.angle, { seat0, seat1 });
await browser.close();
check("без ошибок страницы", errors.length === 0, errors);
for (const c of checks) console.log(c.ok ? "ok  " : "FAIL", c.name, c.ok ? "" : JSON.stringify(c.got));
process.exit(checks.every((c) => c.ok) ? 0 : 1);
