// GLYPHS OF THE DECK'S FONT, AS BITMAPS — a one-time capture, checked in as `src/decks/glyphs.ts`.
//
// 'Press Start 2P' is a pixel font: every glyph is an 8×8 grid of cells. A face texture is an SVG
// document loaded as an IMAGE, and an image cannot reach a page's fonts — so the deck cannot set
// its index in the font at runtime, and a baking script on a machine without the font cannot
// either. Captured once as cells, the index is drawn as rects: no font anywhere, identical pixels
// everywhere, and the vector and the baked raster can never disagree about a letter.
//
// Run: `node scripts/glyphs.mjs` (from `game-presets/cards`). Needs the network once, for the font.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

/** Every character a face can show: Latin ranks, JOKER and the brand words, the Cyrillic ranks and «Джокер». */
const CHARS = [..."A2345678910JQK", ..."JOKER", ..."CROSSADE DECK".replace(" ", ""), ..."ТВДК", ..."Джокер"];
const CELL = 10;
const OUT = fileURLToPath(new URL("../src/decks/glyphs.ts", import.meta.url));

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent(`<!doctype html><html><head>
<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
</head><body></body></html>`);
// The font arrives in SUBSETS (Latin, Cyrillic) and a bare `load` fetches only the Latin one —
// the text is what asks for the rest.
await page.evaluate(async (text) => {
  await document.fonts.load("80px 'Press Start 2P'", text);
  await document.fonts.ready;
}, CHARS.join(""));

const cells = await page.evaluate(
  ({ chars, cell }) => {
    const font = `${cell * 8}px 'Press Start 2P'`;
    const out = {};
    for (const ch of [...new Set(chars)]) {
      const canvas = document.createElement("canvas");
      canvas.width = cell * 12;
      canvas.height = cell * 12;
      const ctx = canvas.getContext("2d");
      ctx.font = font;
      ctx.fillStyle = "#000";
      ctx.textBaseline = "alphabetic";
      // The em box is 8 cells: the baseline sits under row 6, row 7 is the descender's. Measured:
      // an 80px em puts cap ink at y 20..89 with the baseline at 100, and Д's feet at 90..99.
      ctx.fillText(ch, cell * 2, cell * 10);
      const px = ctx.getImageData(0, 0, canvas.width, canvas.height).data;
      const rows = [];
      for (let r = 0; r < 8; r++) {
        let row = "";
        for (let c = 0; c < 8; c++) {
          const x = cell * 2 + c * cell + cell / 2;
          const y = cell * 2 + r * cell + cell / 2;
          row += px[(y * canvas.width + x) * 4 + 3] > 128 ? "#" : ".";
        }
        rows.push(row);
      }
      out[ch] = rows;
    }
    return out;
  },
  { chars: CHARS, cell: CELL },
);
await browser.close();

const empty = Object.entries(cells).filter(([, rows]) => rows.every((r) => !r.includes("#")));
if (empty.length) throw new Error(`no ink for: ${empty.map(([c]) => c).join(" ")}`);

const body = Object.entries(cells)
  .map(([ch, rows]) => `  ${JSON.stringify(ch)}: [${rows.map((r) => JSON.stringify(r)).join(", ")}],`)
  .join("\n");
writeFileSync(
  OUT,
  `// GENERATED by \`scripts/glyphs.mjs\` — the deck's index font, 'Press Start 2P', captured as 8×8
// cells so a face texture can draw its letters as rects and never depend on a font being installed.
// Row 7 is the cell below the baseline (a Q's tail, a Д's feet); rows 0..6 are the cap height.

/** A glyph: eight rows of eight cells, \`#\` ink and \`.\` paper. Every glyph advances one em. */
export type Glyph = readonly [string, string, string, string, string, string, string, string];

export const GLYPHS: Readonly<Record<string, Glyph>> = {
${body}
};
`,
);
console.log(`wrote ${Object.keys(cells).length} glyphs → ${OUT}`);
