// СТРАНИЦА ХОЗЯИНА — «Спрайты» → «Все спрайты»: плоская библиотека картинок. Загрузить SVG / PNG — картинка в «Своих»
// со своим именем; SVG со скриптом не берётся; поиск по имени; встроенные (колода, файлы, код) — рядом, испечены;
// тап — крупно в трёх расцветках, влезает в телефон; свою — переименовать и удалить. Без ключа библиотека закрыта.
//   node scripts/tableAdminGallery.mjs [base] [secret] [shot.png]
import { writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createRequire } from "module";
const require = createRequire(process.env.PW_FROM ?? import.meta.url);
const { chromium } = require("playwright");

const base = process.argv[2] ?? "http://localhost:2611";
const secret = process.argv[3] ?? "probe";
const shot = process.argv[4];
const tag = `zz${Date.now().toString(36)}`;
const good = join(tmpdir(), `${tag}-лис.svg`), evil = join(tmpdir(), `${tag}-зло.svg`);
await writeFile(good, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="#b3221f" stroke="#0b0704" stroke-width="3"/></svg>`);
await writeFile(evil, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><script>alert(1)</script></svg>`);
const checks = [];
const check = (name, ok, got) => checks.push({ name, ok, got });
const own = async () => (await (await fetch(`${base}/table/admin/lib`, { headers: { "x-table-secret": secret } })).json()).sprites.filter((x) => x.name.startsWith(tag));

const browser = await chromium.launch();
const p = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
p.on("pageerror", (e) => errors.push(e.message));
p.on("dialog", (d) => d.accept());
try {
  await p.goto(`${base}/table/admin#key=${encodeURIComponent(secret)}`);
  await p.waitForSelector(".sg .cell");
  await p.waitForFunction(() => document.querySelectorAll(".sg .cell .wait").length === 0, null, { timeout: 20_000 }).catch(() => {});
  const cells = await p.locator(".sg .cell").count();
  check("встроенные на месте и испечены", cells >= 60 && (await p.locator(".sg .cell .wait").count()) === 0, cells);
  // ФИЛЬТР — ОДНО ПОЛЕ: «ключ:значения», Enter — условие становится чипом
  const filt = async (text) => { await p.fill("[data-q]", text); await p.press("[data-q]", "Enter"); await p.waitForTimeout(150); };
  const clear = async () => { if (await p.locator("[data-clear]").count()) await p.click("[data-clear]"); await p.fill("[data-q]", ""); };
  const captions = () => p.locator(".sg .cell i:not(.fmt)").allTextContents();
  await filt("деталь:ноги");
  const legs = await captions();
  check("«деталь:ноги» — только ноги, условие — чипом, поле пустое", legs.length > 0 && legs.every((t) => t.startsWith("ноги")) && (await p.locator('[data-chip="gk"]').count()) === 1 && (await p.inputValue("[data-q]")) === "", legs);
  await clear();
  await filt("деталь:голова,тело сторона:спина");
  const backs = await captions();
  check("«деталь:голова,тело сторона:спина» — внутри ключа «или», между — «и»", backs.length > 0 && backs.every((t) => /^(голова|тело) · спина/.test(t)) && backs.some((t) => t.startsWith("тело")) && backs.some((t) => t.startsWith("голова")), backs);
  await p.locator('[data-chip="gk"] [data-chip-v="body"]').click();
  const noBody = await captions();
  check("крестик у значения в чипе убирает только его", noBody.length > 0 && noBody.every((t) => t.startsWith("голова · спина")), noBody);
  await filt('тег:"Король треф"');
  const kings = await p.locator(".sg .cell b").allTextContents();
  check("тег из двух слов — в кавычках, чипом", kings.length === 1 && kings[0].startsWith("Король треф") && (await p.locator('[data-chip="gt"] [data-chip-v="Король треф"]').count()) === 1 && (await p.inputValue("[data-q]")) === "", [kings, await p.inputValue("[data-q]")]);
  await clear();
  await filt("формат:svg");
  const svgs = await p.locator(".sg .cell i.fmt").allTextContents();
  check("«формат:svg» — только SVG", svgs.length > 0 && svgs.every((t) => t.startsWith("SVG")), svgs.slice(0, 5));
  await clear();
  await filt("формат:png");
  const pngs = await p.locator(".sg .cell i.fmt").allTextContents();
  check("«формат:png» — только PNG, и они не красятся", pngs.length > 0 && pngs.every((t) => t === "PNG · не красится"), pngs);
  await clear();
  // ВЫПАДАШКИ: кнопка на ключ, внутри — все значения галочками со счётчиками
  check("кнопки всех ключей на виду", (await p.locator("[data-drop]").allTextContents()).map((t) => t.replace(" ▾", "")).join() === "Деталь,Сторона,Формат,Откуда,Красится,Тег", await p.locator("[data-drop]").allTextContents());
  await p.click('[data-drop="gc"]');
  const rows = await p.locator("[data-dmenu] .drow span").allTextContents();
  const inScreen = await p.evaluate(() => { const r = document.querySelector("[data-dmenu]").getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth; });
  check("меню выпадашки целиком в экране телефона", inScreen, await p.evaluate(() => document.querySelector("[data-dmenu]").getBoundingClientRect().toJSON()));
  check("в выпадашке — все значения, угадывать нечего", rows.join() === "да,нет", rows);
  const noRow = p.locator("[data-dmenu] .drow", { hasText: "нет" });
  const sugN = Number(await noRow.locator("small").innerText());
  await noRow.locator("input").check();
  await p.waitForTimeout(150);
  check("галочка — условие: счётчик = сколько покажет, кнопка и чип говорят, что выбрано", sugN > 0 && sugN === (await p.locator(".sg .cell").count()) && (await p.locator('[data-chip="gc"]').count()) === 1 && /Красится: нет/.test(await p.locator('[data-drop="gc"]').innerText()) && (await p.locator("[data-dmenu]").count()) === 1, sugN);
  await p.click('[data-drop="gt"]');
  await p.fill("[data-dfind]", "корол");
  const kingsTags = await p.locator("[data-dmenu] .drow span").allTextContents();
  check("у тегов — поиск внутри выпадашки", kingsTags.length >= 4 && kingsTags.every((t) => /король/i.test(t)), kingsTags);
  await p.click("h1, .count", { force: true }).catch(() => {});
  await p.locator(".count").click();
  check("тап мимо — выпадашка закрыта", (await p.locator("[data-dmenu]").count()) === 0, null);
  await clear();
  await filt("деталь:голова сторона:лицо");
  check("загрузка ляжет туда, что выбрано", /голова · лицо/.test(await p.textContent("[data-into]")), await p.textContent("[data-into]"));
  await p.setInputFiles("[data-file]", [good, evil]);
  await p.waitForFunction(() => /Загружено/.test(document.querySelector("[data-said]")?.textContent ?? ""), null, { timeout: 8000 }).catch(() => {});
  const said = await p.textContent("[data-said]");
  check("чистый SVG взят, со скриптом — нет, и сказано почему", /Загружено 1/.test(said) && /unsafe_svg/.test(said), said);
  const mine = await own();
  check("в библиотеке — одна картинка, имя из файла, деталь и сторона — из полок", mine.length === 1 && mine[0].name === `${tag}-лис` && mine[0].origin === "upload" && mine[0].slot === "head" && mine[0].side === "front", mine);
  const file = await fetch(`${base}/table/lib/${mine[0].id}.svg`);
  check("файл отдаётся всем, открытый напрямую ничего не исполняет", file.status === 200 && /default-src 'none'/.test(file.headers.get("content-security-policy") ?? ""), file.headers.get("content-security-policy"));
  await clear();
  await filt(`откуда:загружены ${tag}`);
  check("«откуда:загружены» и поиск — только она", (await p.locator(".sg .cell").count()) === 1 && (await p.locator(".sg .cell i").first().innerText()) === "голова · лицо · загружен", await p.locator(".sg .grid").innerText());
  // СТРАНИЦА СПРАЙТА: своя картинка
  await p.locator(".sg .cell").first().click();
  await p.waitForSelector("[data-sprite-page] [data-big][src]");
  check("тап — страница спрайта вместо галереи", (await p.locator("[data-list]").isHidden()) && (await p.locator("[data-sprite-page]").count()) === 1, null);
  const st = await p.locator("[data-stage3d]").boundingBox();
  const ry0 = await p.getAttribute("[data-stage3d]", "data-ry");
  await p.mouse.move(st.x + st.width / 2, st.y + st.height / 2);
  await p.mouse.down();
  await p.mouse.move(st.x + st.width / 2 + 100, st.y + st.height / 2 - 40, { steps: 5 });
  await p.mouse.up();
  check("крутится пальцем", (await p.getAttribute("[data-stage3d]", "data-ry")) !== ry0, [ry0, await p.getAttribute("[data-stage3d]", "data-ry")]);
  const src0 = await p.getAttribute("[data-big]", "src");
  await p.click('[data-pal16="5"]');
  const src1 = await p.getAttribute("[data-big]", "src");
  check("расцветка меняет картинку; все 16 — рядом", src1 !== src0 && (await p.locator("[data-pal16] img[src]").count()) === 16, null);
  await p.waitForFunction(() => !document.querySelector("[data-c]")?.disabled, null, { timeout: 5000 }).catch(() => {});
  await p.fill('[data-c="0"]', "#ff00aa");
  check("свои цвета красят SVG", decodeURIComponent(await p.getAttribute("[data-big]", "src")).includes("#ff00aa"), null);
  if (shot) await p.screenshot({ path: shot, fullPage: true });
  // CRUD НА СТРАНИЦЕ: «как новый» — копия с покраской; «заменить файл» — та же запись, новая картинка
  await p.click("[data-sprite-page] [data-copy]");
  await p.waitForFunction((t) => document.querySelector("[data-sprite-page] [data-name]")?.value.includes("(копия)"), tag, { timeout: 5000 }).catch(() => {});
  const copy = (await own()).find((x) => x.name.endsWith("(копия)"));
  const copyText = copy ? await (await fetch(`${base}/table/lib/${copy.id}.svg`)).text() : "";
  check("«Сохранить как новый» — копия с нынешней покраской, открыта её страница", !!copy && copyText.toLowerCase().includes("#ff00aa") && copy.slot === "head" && copy.side === "front", copy);
  await p.setInputFiles("[data-sprite-page] [data-replace-file]", { name: "new.svg", mimeType: "image/svg+xml", buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="80" height="80" x="10" y="10" fill="#1d4f80"/></svg>') });
  await p.waitForFunction(() => /заменён/.test(document.querySelector("[data-act-said]")?.textContent ?? ""), null, { timeout: 5000 }).catch(() => {});
  const replaced = copy ? await (await fetch(`${base}/table/lib/${copy.id}.svg`)).text() : "";
  check("«Заменить файл» — та же запись, новая картинка", replaced.includes("<rect") && (await own()).some((x) => x.id === copy?.id && x.name === copy.name), replaced.slice(0, 80));
  await p.click("[data-sprite-page] [data-drop]");
  await p.waitForTimeout(600);
  check("удалить копию — «назад» к спрайту, с которого её сделали", (await p.inputValue("[data-sprite-page] [data-name]").catch(() => "")) === `${tag}-лис` && !(await own()).some((x) => x.id === copy?.id), await p.inputValue("[data-sprite-page] [data-name]").catch(() => null));
  await p.fill("[data-sprite-page] [data-name]", `${tag} Лис`);
  await p.click('[data-sprite-page] [data-pick-kind] [data-v="hair"]');
  await p.click('[data-sprite-page] [data-pick-side] [data-v=""]');
  await p.fill("[data-sprite-page] [data-tags]", "Лис, звери");
  await p.click("[data-sprite-page] [data-save]");
  await p.waitForTimeout(600);
  const edited = (await own())[0];
  check("переименовать, сменить деталь, сторону, теги", edited?.name === `${tag} Лис` && edited.slot === "hair" && edited.side === null && edited.tags.join() === "Лис,звери", edited);
  await p.click("[data-sprite-page] [data-drop]");
  await p.waitForTimeout(600);
  check("удалить — назад к галерее, файла больше нет", (await own()).length === 0 && (await fetch(`${base}/table/lib/${mine[0].id}.svg`)).status === 404 && (await p.locator("[data-list]").isVisible()), await own());
  // встроенная: король треф, лицо — похожие по тегу, свои цвета недоступны
  await clear();
  await filt('откуда:колода деталь:голова сторона:лицо тег:"Король треф"');
  await p.locator(".sg .cell").first().click();
  await p.waitForSelector("[data-sprite-page]");
  await p.waitForFunction(() => /не SVG/.test(document.querySelector("[data-own3-said]")?.textContent ?? ""), null, { timeout: 5000 }).catch(() => {});
  check("встроенную не удалить; у колоды свои цвета не выбрать, и сказано почему", (await p.locator("[data-sprite-page] [data-drop]").count()) === 0 && (await p.locator("[data-c]").first().isDisabled()), await p.textContent("[data-own3-said]"));
  await p.click('[data-pal16="1"]');
  await p.click("[data-sprite-page] [data-copy]");
  await p.waitForSelector("[data-sprite-page] [data-name]", { timeout: 5000 }).catch(() => {});
  const kingCopy = (await (await fetch(`${base}/table/admin/lib`, { headers: { "x-table-secret": secret } })).json()).sprites.find((x) => x.name === "Король треф · лицо");
  check("встроенную — «Сделать своей копией»: PNG с покраской, та же деталь, сторона, теги", kingCopy?.ext === "png" && kingCopy.slot === "head" && kingCopy.side === "front" && kingCopy.tags.includes("Король треф") && (await fetch(`${base}/table/lib/${kingCopy.id}.png`)).status === 200, kingCopy);
  if (kingCopy) await fetch(`${base}/table/admin/lib/${kingCopy.id}`, { method: "DELETE", headers: { "x-table-secret": secret } });
  await p.goBack();
  await p.waitForSelector("[data-sprite-page] h2");
  const sims = await p.locator("[data-similar] .cell b").allTextContents();
  check("похожие по тегам — вторая сторона того же короля", sims.includes("Король треф · спина"), sims);
  await p.locator("[data-similar] .cell", { hasText: "Король треф · спина" }).first().click();
  check("тап по похожему — его страница", /Король треф · спина/.test(await p.locator("[data-sprite-page] h2").innerText()), null);
  await p.goBack();
  check("«назад» — к прежнему спрайту", /Король треф · лицо/.test(await p.locator("[data-sprite-page] h2").innerText()), null);
  await p.click("[data-back]");
  check("и ещё назад — галерея", await p.locator("[data-list]").isVisible(), null);
  check("без ключа библиотека закрыта", (await fetch(`${base}/table/admin/lib`)).status === 403, null);
  check("без ошибок на странице", errors.length === 0, errors);
} finally {
  await browser.close();
  for (const x of await own()) await fetch(`${base}/table/admin/lib/${x.id}`, { method: "DELETE", headers: { "x-table-secret": secret } });
}
for (const c of checks) console.log(`${c.ok ? "✓" : "✗"} ${c.name}${c.ok ? "" : ` — ${JSON.stringify(c.got).slice(0, 400)}`}`);
const bad = checks.filter((c) => !c.ok).length;
console.log(`${checks.length - bad}/${checks.length}`);
process.exit(bad ? 1 : 0);
