// СТРАНИЦА ХОЗЯИНА — «Спрайты» → «Все спрайты»: плоская библиотека картинок. Загрузить SVG / PNG — картинка в «Своих»
// со своим именем; SVG со скриптом не берётся; поиск по имени; встроенные (колода, файлы, код — все SVG) — рядом, испечены;
// тап — крупно в трёх расцветках, влезает в телефон; свою — переименовать и удалить. Без ключа библиотека закрыта.
//   node scripts/tableAdminGallery.mjs [base] [secret] [shot.png]
import { writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createRequire } from "module";
const require = createRequire(process.env.PW_FROM ?? import.meta.url);
const { chromium } = require("playwright");

const base = process.argv[2] ?? "http://localhost:2611";
const secret = process.argv[3] ?? "probe";
const shot = process.argv[4];
const tag = `zz${Date.now().toString(36)}`;
const good = join(tmpdir(), `${tag}-лис.svg`), evil = join(tmpdir(), `${tag}-зло.svg`);
await writeFile(good, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="#b3221f" stroke="#0b0704" stroke-width="3"/></svg>`);
await writeFile(evil, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><script>alert(1)</script></svg>`);
const checks = [];
const check = (name, ok, got) => checks.push({ name, ok, got });
const own = async () => (await (await fetch(`${base}/table/admin/lib`, { headers: { "x-table-secret": secret } })).json()).sprites.filter((x) => x.name.startsWith(tag));

const browser = await chromium.launch();
const p = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
p.on("pageerror", (e) => errors.push(e.message));
p.on("dialog", (d) => d.accept());
try {
  await p.goto(`${base}/table/admin#key=${encodeURIComponent(secret)}`);
  await p.waitForSelector(".sg .cell");
  await p.waitForFunction(() => document.querySelectorAll(".sg .cell .wait").length === 0, null, { timeout: 20_000 }).catch(() => {});
  const cells = await p.locator(".sg .cell").count();
  check("встроенные на месте и испечены", cells >= 60 && (await p.locator(".sg .cell .wait").count()) === 0, cells);
  // ФИЛЬТР — ОДНО ПОЛЕ: «ключ:значения», Enter — условие становится чипом
  const filt = async (text) => { await p.fill("[data-q]", text); await p.press("[data-q]", "Enter"); await p.waitForTimeout(150); };
  const clear = async () => { if (await p.locator("[data-clear]").count()) await p.click("[data-clear]"); await p.fill("[data-q]", ""); };
  const captions = () => p.locator(".sg .cell i:not(.fmt)").allTextContents();
  await filt("деталь:ноги");
  const legs = await captions();
  check("«деталь:ноги» — только ноги, условие — чипом, поле пустое", legs.length > 0 && legs.every((t) => t.startsWith("ноги")) && (await p.locator('[data-chip="gk"]').count()) === 1 && (await p.inputValue("[data-q]")) === "", legs);
  await clear();
  await filt("деталь:голова,тело сторона:спина");
  const backs = await captions();
  check("«деталь:голова,тело сторона:спина» — внутри ключа «или», между — «и»", backs.length > 0 && backs.every((t) => /^(голова|тело) · спина/.test(t)) && backs.some((t) => t.startsWith("тело")) && backs.some((t) => t.startsWith("голова")), backs);
  await p.locator('[data-chip="gk"] [data-chip-v="body"]').click();
  const noBody = await captions();
  check("крестик у значения в чипе убирает только его", noBody.length > 0 && noBody.every((t) => t.startsWith("голова · спина")), noBody);
  await filt('тег:"Король треф"');
  const kings = await p.locator(".sg .cell b").allTextContents();
  check("тег из двух слов — в кавычках, чипом", kings.length === 1 && kings[0].startsWith("Король треф") && (await p.locator('[data-chip="gt"] [data-chip-v="Король треф"]').count()) === 1 && (await p.inputValue("[data-q]")) === "", [kings, await p.inputValue("[data-q]")]);
  await clear();
  await filt("формат:svg");
  const svgs = await p.locator(".sg .cell i.fmt").allTextContents();
  check("«формат:svg» — только SVG", svgs.length > 0 && svgs.every((t) => t.startsWith("SVG")), svgs.slice(0, 5));
  const svgNames = await p.locator(".sg .cell b").allTextContents();
  check("колода и рисунки кода — тоже SVG: форматов только два", svgNames.some((t) => t.startsWith("Король треф")) && svgNames.some((t) => t.startsWith("Шар")) && !svgs.some((t) => /код/.test(t)), svgNames.slice(0, 8));
  await clear();
  await filt("формат:png");
  const pngs = await p.locator(".sg .cell i.fmt").allTextContents();
  check("«формат:png» — только PNG, и они не красятся", pngs.length > 0 && pngs.every((t) => t === "PNG · не красится"), pngs);
  await clear();
  // ЛИЦА КОЛОДЫ: бумага вокруг фигуры прозрачная, а лицо — нет (бумага не протекает внутрь сквозь щели контура)
  await filt("откуда:колода деталь:голова сторона:лицо");
  await p.waitForFunction(() => document.querySelectorAll(".sg .cell img").length === 12, null, { timeout: 15000 }).catch(() => {});
  const holes = await p.locator(".sg .cell").evaluateAll(async (cells) => Promise.all(cells.map(async (c) => {
    const img = c.querySelector("img");
    if (!img) return [c.querySelector("b").textContent, 1];
    await img.decode();
    const cv = document.createElement("canvas");
    cv.width = img.naturalWidth; cv.height = img.naturalHeight;
    const g = cv.getContext("2d");
    g.drawImage(img, 0, 0);
    const [x, y, w, h] = [cv.width * 0.3, cv.height * 0.3, cv.width * 0.4, cv.height * 0.35].map(Math.round);
    const d = g.getImageData(x, y, w, h).data;
    let clear = 0;
    for (let i = 3; i < d.length; i += 4) if (d[i] < 128) clear += 1;
    return [c.querySelector("b").textContent, Math.round((clear / (w * h)) * 1000) / 1000];
  })));
  check("лица колоды целые: посреди лица нет дыр насквозь", holes.length === 12 && holes.every(([, f]) => f < 0.01), holes.filter(([, f]) => f >= 0.01));
  await clear();
  // ОДНО ПОЛЕ: в фокусе — все варианты по группам со счётчиками; набранное сужает и сразу ищет по всему
  await p.click("[data-q]");
  const heads = await p.locator("[data-qlist] .qh").allTextContents();
  check("одно поле: в фокусе видно все группы вариантов — угадывать нечего", heads.join() === "деталь,сторона,формат,откуда,красится,тег" && (await p.locator("[data-drop]").count()) === 0, heads);
  const fmts = await p.locator('[data-qi^="gf|"]').evaluateAll((els) => els.map((e) => e.dataset.qi));
  check("в списке формата — только svg и png", fmts.join() === "gf|svg,gf|png", fmts);
  await p.fill("[data-q]", "не");
  const noItem = p.locator('[data-qi="gc|no"]');
  const sugN = Number(await noItem.locator("small").innerText());
  await noItem.dispatchEvent("mousedown");
  await p.waitForTimeout(150);
  check("тап по варианту — чип, поле очищено; счётчик = сколько покажет", sugN > 0 && sugN === (await p.locator(".sg .cell").count()) && (await p.locator('[data-chip="gc"]').count()) === 1 && (await p.inputValue("[data-q]")) === "", sugN);
  await clear();
  await p.fill("[data-q]", "голова svg");
  const hs = await p.locator(".sg .cell").allInnerTexts();
  check("набранное ищет по всему на карточке: «голова svg» — головы в SVG", hs.length > 0 && hs.every((t) => /голова/.test(t) && /SVG/.test(t)), hs.slice(0, 3));
  await p.fill("[data-q]", "rjhjkm");
  const ks = await p.locator(".sg .cell b").allTextContents();
  check("в другой раскладке — «rjhjkm» находит королей", ks.length > 0 && ks.every((t) => /Король/.test(t)), ks);
  await p.fill("[data-q]", "треф");
  await p.press("[data-q]", "Enter");
  check("Enter по слову — чип «найти», поле пустое", (await p.locator("[data-term]").count()) === 1 && (await p.inputValue("[data-q]")) === "" && (await p.locator(".sg .cell b").allTextContents()).every((t) => /треф/.test(t)), null);
  await p.click("[data-q]");
  check("тап по полю в фокусе — список снова открыт", await p.locator("[data-qlist]").isVisible(), null);
  await p.keyboard.press("Escape");
  check("Esc — список закрыт", await p.locator("[data-qlist]").isHidden(), null);
  await clear();
  await filt("деталь:голова сторона:лицо");
  check("загрузка ляжет туда, что выбрано", /голова · лицо/.test(await p.textContent("[data-into]")), await p.textContent("[data-into]"));
  await p.setInputFiles("[data-file]", [good, evil]);
  await p.waitForFunction(() => /Загружено/.test(document.querySelector("[data-said]")?.textContent ?? ""), null, { timeout: 8000 }).catch(() => {});
  const said = await p.textContent("[data-said]");
  check("чистый SVG взят, со скриптом — нет, и сказано почему", /Загружено 1/.test(said) && /unsafe_svg/.test(said), said);
  const mine = await own();
  check("в библиотеке — одна картинка, имя из файла, деталь и сторона — из полок", mine.length === 1 && mine[0].name === `${tag}-лис` && mine[0].origin === "upload" && mine[0].slot === "head" && mine[0].side === "front", mine);
  const file = await fetch(`${base}/table/lib/${mine[0].id}.svg`);
  check("файл отдаётся всем, открытый напрямую ничего не исполняет", file.status === 200 && /default-src 'none'/.test(file.headers.get("content-security-policy") ?? ""), file.headers.get("content-security-policy"));
  await clear();
  await filt(`откуда:загружены ${tag}`);
  check("«откуда:загружены» и поиск — только она", (await p.locator(".sg .cell").count()) === 1 && (await p.locator(".sg .cell i").first().innerText()) === "голова · лицо · загружен", await p.locator(".sg .grid").innerText());
  // СТРАНИЦА СПРАЙТА: своя картинка
  await p.locator(".sg .cell").first().click();
  await p.waitForSelector("[data-sprite-page] [data-big][src]");
  check("тап — страница спрайта вместо галереи", (await p.locator("[data-list]").isHidden()) && (await p.locator("[data-sprite-page]").count()) === 1, null);
  // ГДЕ И КАК ЛЕЖИТ: своя — запись, файл на сервере, адрес, вес, рисунок
  const factsOf = async () => { await p.waitForFunction(() => /байт/.test(document.querySelector("[data-facts]")?.textContent ?? ""), null, { timeout: 5000 }).catch(() => {}); return p.evaluate(() => document.querySelector("[data-facts]")?.textContent ?? ""); };
  const ownFacts = await factsOf();
  check("своя: видно запись, файл, адрес, вес и рисунок", ownFacts.includes(`table_sprites · ${mine[0].id}`) && ownFacts.includes(`data/sprite-lib/${mine[0].id}.svg`) && ownFacts.includes(`/table/lib/${mine[0].id}.svg`) && /\d+ байт/.test(ownFacts) && /viewBox/.test(ownFacts) && /ставится в «Деталях»/.test(ownFacts), ownFacts);
  const st = await p.locator("[data-stage3d]").boundingBox();
  const ry0 = await p.getAttribute("[data-stage3d]", "data-ry");
  await p.mouse.move(st.x + st.width / 2, st.y + st.height / 2);
  await p.mouse.down();
  await p.mouse.move(st.x + st.width / 2 + 100, st.y + st.height / 2 - 40, { steps: 5 });
  await p.mouse.up();
  check("крутится пальцем", (await p.getAttribute("[data-stage3d]", "data-ry")) !== ry0, [ry0, await p.getAttribute("[data-stage3d]", "data-ry")]);
  const src0 = await p.getAttribute("[data-big]", "src");
  await p.click('[data-pal16="5"]');
  const src1 = await p.getAttribute("[data-big]", "src");
  check("расцветка меняет картинку; все 16 — рядом", src1 !== src0 && (await p.locator("[data-pal16] img[src]").count()) === 16, null);
  await p.waitForFunction(() => !document.querySelector("[data-c]")?.disabled, null, { timeout: 5000 }).catch(() => {});
  await p.fill('[data-c="0"]', "#ff00aa");
  check("свои цвета красят SVG", decodeURIComponent(await p.getAttribute("[data-big]", "src")).includes("#ff00aa"), null);
  if (shot) await p.screenshot({ path: shot, fullPage: true });
  // CRUD НА СТРАНИЦЕ: «как новый» — копия с покраской; «заменить файл» — та же запись, новая картинка
  await p.click("[data-sprite-page] [data-copy]");
  await p.waitForFunction((t) => document.querySelector("[data-sprite-page] [data-name]")?.value.includes("(копия)"), tag, { timeout: 5000 }).catch(() => {});
  const copy = (await own()).find((x) => x.name.endsWith("(копия)"));
  const copyText = copy ? await (await fetch(`${base}/table/lib/${copy.id}.svg`)).text() : "";
  check("«Сохранить как новый» — копия с нынешней покраской, открыта её страница", !!copy && copyText.toLowerCase().includes("#ff00aa") && copy.slot === "head" && copy.side === "front", copy);
  await p.setInputFiles("[data-sprite-page] [data-replace-file]", { name: "new.svg", mimeType: "image/svg+xml", buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="80" height="80" x="10" y="10" fill="#1d4f80"/></svg>') });
  await p.waitForFunction(() => /заменён/.test(document.querySelector("[data-act-said]")?.textContent ?? ""), null, { timeout: 5000 }).catch(() => {});
  const replaced = copy ? await (await fetch(`${base}/table/lib/${copy.id}.svg`)).text() : "";
  check("«Заменить файл» — та же запись, новая картинка", replaced.includes("<rect") && (await own()).some((x) => x.id === copy?.id && x.name === copy.name), replaced.slice(0, 80));
  await p.click("[data-sprite-page] [data-drop]");
  await p.waitForTimeout(600);
  check("удалить копию — «назад» к спрайту, с которого её сделали", (await p.inputValue("[data-sprite-page] [data-name]").catch(() => "")) === `${tag}-лис` && !(await own()).some((x) => x.id === copy?.id), await p.inputValue("[data-sprite-page] [data-name]").catch(() => null));
  await p.fill("[data-sprite-page] [data-name]", `${tag} Лис`);
  await p.click('[data-sprite-page] [data-pick-kind] [data-v="hair"]');
  await p.click('[data-sprite-page] [data-pick-side] [data-v=""]');
  await p.fill("[data-sprite-page] [data-tags]", "Лис, звери");
  await p.click("[data-sprite-page] [data-save]");
  await p.waitForTimeout(600);
  const edited = (await own())[0];
  check("переименовать, сменить деталь, сторону, теги", edited?.name === `${tag} Лис` && edited.slot === "hair" && edited.side === null && edited.tags.join() === "Лис,звери", edited);
  await p.click("[data-sprite-page] [data-drop]");
  await p.waitForTimeout(600);
  check("удалить — назад к галерее, файла больше нет", (await own()).length === 0 && (await fetch(`${base}/table/lib/${mine[0].id}.svg`)).status === 404 && (await p.locator("[data-list]").isVisible()), await own());
  // встроенная: король треф, лицо — похожие по тегу, свои цвета недоступны
  await clear();
  await filt('откуда:колода деталь:голова сторона:лицо тег:"Король треф"');
  await p.locator(".sg .cell").first().click();
  await p.waitForSelector("[data-sprite-page]");
  await p.waitForFunction(() => !document.querySelector("[data-c]")?.disabled, null, { timeout: 5000 }).catch(() => {});
  const kingSrc = await p.getAttribute("[data-big]", "src");
  await p.fill('[data-c="0"]', "#ff00aa", { timeout: 3000 }).catch(() => {});
  await p.waitForFunction((was) => { const src = document.querySelector("[data-big]")?.getAttribute("src"); return src && src !== was; }, kingSrc, { timeout: 5000 }).catch(() => {});
  check("встроенную не удалить; колода красится своими цветами", (await p.locator("[data-sprite-page] [data-drop]").count()) === 0 && (await p.getAttribute("[data-big]", "src")) !== kingSrc, await p.textContent("[data-own3-said]"));
  await p.click('[data-pal16="1"]');
  await p.click("[data-sprite-page] [data-copy]");
  await p.waitForSelector("[data-sprite-page] [data-name]", { timeout: 5000 }).catch(() => {});
  const kingCopy = (await (await fetch(`${base}/table/admin/lib`, { headers: { "x-table-secret": secret } })).json()).sprites.find((x) => x.name === "Король треф · лицо");
  check("встроенную — «Сделать своей копией»: PNG с покраской, та же деталь, сторона, теги", kingCopy?.ext === "png" && kingCopy.slot === "head" && kingCopy.side === "front" && kingCopy.tags.includes("Король треф") && (await fetch(`${base}/table/lib/${kingCopy.id}.png`)).status === 200, kingCopy);
  if (kingCopy) await fetch(`${base}/table/admin/lib/${kingCopy.id}`, { method: "DELETE", headers: { "x-table-secret": secret } });
  await p.goBack();
  await p.waitForSelector("[data-sprite-page] h2");
  // нарисованное кодом — тоже SVG: свои цвета прямо в рисунке
  await p.goBack();
  await p.waitForSelector("[data-list]:not([hidden])").catch(() => {});
  await clear();
  await filt("Бочонок");
  await p.locator(".sg .cell").first().click();
  await p.waitForFunction(() => !document.querySelector("[data-c]")?.disabled, null, { timeout: 5000 }).catch(() => {});
  await p.fill('[data-c="1"]', "#00ffaa", { timeout: 3000 }).catch(() => {});
  check("рисунок кода (бочонок) красится своими цветами", decodeURIComponent((await p.getAttribute("[data-big]", "src")) ?? "").includes("#00ffaa"), await p.textContent("[data-own3-said]"));
  const barrelFacts = await factsOf();
  check("рисунок кода: где функция и какой рисунок", barrelFacts.includes("table-client/skinArt.ts") && barrelFacts.includes("barrel") && barrelFacts.includes("barrel:body") && /повёрнута на \d+°/.test(barrelFacts), barrelFacts);
  await p.goBack();
  await clear();
  await filt('откуда:колода деталь:голова сторона:лицо тег:"Король треф"');
  await p.locator(".sg .cell").first().click();
  await p.waitForSelector("[data-sprite-page] h2");
  const kingFacts = await factsOf();
  check("колода: из какой карты, каким куском, куда смотрит, как стоит к камере, подстройка", kingFacts.includes("table-client/sprites/club-K.svg") && kingFacts.includes("28, 0, 70, 58") && /бумажный/.test(kingFacts) && /масштаб ×1/.test(kingFacts) && /2\.40 ×/.test(kingFacts) && /king:head|club-K:head/.test(kingFacts), kingFacts);
  // СЛОИ: оси фигуры, клетка в единицу стола, размер — каждый включается сам
  const axT = (k) => p.getAttribute(`[data-ax="${k}"]`, "style");
  check("оси у «лица»: перед — к зрителю, верх — вверх, право фигуры — влево по картинке", /rotateY\(-90deg\)/.test(await axT("front")) && /rotateZ\(-90deg\)/.test(await axT("up")) && /rotateZ\(180deg\)/.test(await axT("right")) && (await p.locator("[data-axes]").isVisible()), [await axT("front"), await axT("up"), await axT("right")]);
  await p.waitForFunction(() => document.querySelector("[data-stage3d]")?.dataset.units, null, { timeout: 5000 }).catch(() => {});
  check("размер за столом — в единицах, по детали", /^2\.40x/.test(await p.getAttribute("[data-stage3d]", "data-units")) && /2\.40 ×/.test(await p.textContent("[data-size]")), await p.textContent("[data-size]"));
  await p.click('[data-layer="axes"]');
  await p.click('[data-layer="grid"]');
  await p.click('[data-layer="size"]');
  const cellBg = await p.evaluate(() => getComputedStyle(document.querySelector("[data-cells]")).backgroundSize);
  check("каждый слой выключается и включается сам: оси — нет, клетка — да, размер — нет", (await p.locator("[data-axes]").isHidden()) && (await p.locator("[data-cells]").isVisible()) && (await p.textContent("[data-size]")) === "" && /px/.test(cellBg), cellBg);
  await p.reload();
  await p.waitForSelector("[data-sprite-page]");
  await p.waitForTimeout(800);
  check("слои переживают обновление", (await p.locator("[data-axes]").isHidden()) && (await p.locator("[data-cells]").isVisible()) && (await p.locator('[data-layer="size"].on').count()) === 0, null);
  for (const k of ["axes", "grid", "size"]) await p.click(`[data-layer="${k}"]`);
  const sims = await p.locator("[data-similar] .cell b").allTextContents();
  check("похожие по тегам — вторая сторона того же короля", sims.includes("Король треф · спина"), sims);
  await p.locator("[data-similar] .cell", { hasText: "Король треф · спина" }).first().click();
  check("тап по похожему — его страница", /Король треф · спина/.test(await p.locator("[data-sprite-page] h2").innerText()), null);
  await p.goBack();
  check("«назад» — к прежнему спрайту", /Король треф · лицо/.test(await p.locator("[data-sprite-page] h2").innerText()), null);
  await p.click("[data-back]");
  check("и ещё назад — галерея", await p.locator("[data-list]").isVisible(), null);
  check("без ключа библиотека закрыта", (await fetch(`${base}/table/admin/lib`)).status === 403, null);
  check("без ошибок на странице", errors.length === 0, errors);
} finally {
  await browser.close();
  for (const x of await own()) await fetch(`${base}/table/admin/lib/${x.id}`, { method: "DELETE", headers: { "x-table-secret": secret } });
}
for (const c of checks) console.log(`${c.ok ? "✓" : "✗"} ${c.name}${c.ok ? "" : ` — ${JSON.stringify(c.got).slice(0, 400)}`}`);
const bad = checks.filter((c) => !c.ok).length;
console.log(`${checks.length - bad}/${checks.length}`);
process.exit(bad ? 1 : 0);
